[package]
name = "puzzle24"
authors = ["Dennis Sprokholt <me@dennis.life>"]
description = "Library for solving Twenty-Four Sliding Puzzles"
readme = "README.md"
license = "MIT"
repository = "https://github.com/sourcedennis/puzzle24"
edition = "2021"
version = "0.1.0"

[dependencies]
